version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Japan
  open-pull-requests-limit: 10
  reviewers:
  - phanect
  assignees:
  - phanect
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: vnu-jar
    versions:
    - 21.2.5
